### ISSUE TITLE
[BUG] NullPointerExceptions (in Path finding ?)

### ISSUE THREAD

**Issue by Pairoba** [AMPZNetwork/Fossilized#5]
**Describe the bug**
NullPointerException

**To Reproduce**
1. play
2. server crash

**Expected behavior**
No server crash

**Crash Log**
```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.PathHeap.func_75846_b(SourceFile:118)
	at net.minecraft.pathfinding.PathHeap.func_75844_c(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186335_a(SourceFile:66)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:40)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:65)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at mod.reborn.server.entity.AmfibianDinosaurEntity$MoveUnderwaterEntityAI.func_75249_e(AmfibianDinosaurEntity.java:163)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at mod.reborn.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:758)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at mod.reborn.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1090)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: rebornmod:entities.beelzebufo (mod.reborn.server.entity.dinosaur.BeelzebufoEntity)
	Entity ID: 5995
	Entity Name: Beelzebufo
	Entity's Exact location: -812,29, 29,00, -929,71
	Entity's Block location: World: (-813,29,-930), Chunk: (at 3,1,14 in -51,-59; contains blocks -816,0,-944 to -801,255,-929), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Entity's Momentum: 0,00, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

```

**Basic Informations:**
 - Server OS: Debian
 - Fossilized Version: 1.8.1b
 - Platform: Technic Launcher
 - Extra mods added by you: none

**Comment by Pairoba** [comment]
Another crash followed: 

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.WalkNodeProcessor.func_176163_a(WalkNodeProcessor.java:36)
	at net.minecraft.pathfinding.PathFinder.func_186334_a(SourceFile:42)
	at net.minecraft.pathfinding.PathFinder.func_186336_a(SourceFile:30)
	at net.minecraft.pathfinding.PathNavigate.func_179680_a(SourceFile:114)
	at net.minecraft.pathfinding.PathNavigateGround.func_179680_a(SourceFile:51)
	at net.minecraft.pathfinding.PathNavigate.func_75488_a(SourceFile:93)
	at net.minecraft.pathfinding.PathNavigate.func_75492_a(SourceFile:143)
	at mod.reborn.server.entity.ai.DinosaurWanderEntityAI.func_75249_e(DinosaurWanderEntityAI.java:94)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at mod.reborn.server.entity.DinosaurEntity.func_70636_d(DinosaurEntity.java:758)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at mod.reborn.server.entity.DinosaurEntity.func_70071_h_(DinosaurEntity.java:1090)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: rebornmod:entities.beelzebufo (mod.reborn.server.entity.dinosaur.BeelzebufoEntity)
	Entity ID: 1261
	Entity Name: Beelzebufo
	Entity's Exact location: -865,75, 62,00, -874,46
	Entity's Block location: World: (-866,62,-875), Chunk: (at 14,3,5 in -55,-55; contains blocks -880,0,-880 to -865,255,-865), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Entity's Momentum: 0,04, -0,08, 0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Comment by LabsZero** [comment]
We are aware of this issue but there is not much we can do.  Try reporting it to the mod developers.
